export const CITY = 'CITY';
export const SORT = 'SORT';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_REGISTER = 'USER_REGISTER';

export const HOUSE_CLASSIFY = 'HOUSE_CLASSIFY';
export const GET_HOUSE_MORE = 'GET_HOUSE_MORE';
export const GET_MY_REPLEASE_SHOW = 'GET_MY_REPLEASE_SHOW';
export const GET_MY_REPLEASE_AUDITING= 'GET_MY_REPLEASE_AUDITING';
export const GET_MY_COLLECTION= 'GET_MY_COLLECTION';

export const GET_HOUSE_LIST = 'GET_HOUSE_LIST';
